# Generated by Django 3.1.2 on 2020-10-30 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('location', models.CharField(blank=True, max_length=15, verbose_name='Город')),
                ('description', models.TextField(blank=True, verbose_name='Информация о компании')),
                ('logo', models.ImageField(blank=True, upload_to='company', verbose_name='Логотип')),
                ('employee_count', models.PositiveIntegerField(default=1, verbose_name='Количество сотрудников')),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('code', models.CharField(blank=True, max_length=15, verbose_name='Код')),
                ('picture', models.ImageField(blank=True, upload_to='speciality', verbose_name='Лого')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название вакансии')),
                ('skills', models.CharField(blank=True, max_length=500, verbose_name='Навыки')),
                ('published_at', models.DateField(auto_now_add=True, verbose_name='Дата размещения')),
                ('text', models.TextField(blank=True, verbose_name='Описание')),
                ('salary_min', models.IntegerField(blank=True, null=True, verbose_name='Зарплата от')),
                ('salary_max', models.IntegerField(blank=True, null=True, verbose_name='Зарплата до')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancy.company')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancy.speciality')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('status', models.CharField(choices=[('NOT LOOKING FOR', 'Не ищу работу'), ('CONSIDERING OFFER', 'Рассматриваю предложения'), ('LOOKING FOR', 'Ищу работу')], default='LOOKING FOR', max_length=100, verbose_name='Готовность к работе')),
                ('salary', models.PositiveIntegerField(blank=True, null=True, verbose_name='Вознаграждение')),
                ('grade', models.CharField(choices=[('TRAINEE', 'Стажер'), ('JUNIOR', 'Джуниор'), ('MIDDLE', 'Миддл'), ('SENIOR', 'Синьор'), ('TEAMLED', 'Лид')], default='JUNIOR', max_length=50, verbose_name='Квалификация')),
                ('education', models.TextField(blank=True, verbose_name='Образование')),
                ('experience', models.TextField(blank=True, verbose_name='Опыт работы')),
                ('portfolio', models.URLField(blank=True, max_length=250, verbose_name='Портфолио')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='vacancy.speciality', verbose_name='Специализация')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_username', models.CharField(max_length=30, verbose_name='Имя')),
                ('written_phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('written_cover_letter', models.TextField(verbose_name='Сопроводительное письмо')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='vacancy.vacancy')),
            ],
        ),
    ]
